### ISSUE TITLE
Compatibility Issue with PhpStorm 2024.2

### ISSUE THREAD

**Issue by MariyaFilippova** [nvelychenko/drupal-extend#75]
Existing versions of the plugin will be marked as incompatible with PS 2024.2 and higher due to API changes in the 2024.2 release. To have a working plugin in PS 2024.2, you don't need to update the source code—just update the versions of the PHP plugin and IntelliJ platform in gradle.properties and release a new plugin version.

Note that according to [IntelliJ Platform](https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html#platformVersions), the Java version should also be changed to 21. Thank you!

**Comment by renebakx** [comment]
Additional to the above, the error that's been thrown by the plugin is
```
Error while indexing /Users/rene.bakx/Projects/Drupal-10-3-project/public/core/modules/ban/ban.module
To reindex this file IDEA has to be restarted

java.lang.NoSuchFieldError: Class com.jetbrains.php.lang.parser.PhpElementTypes does not have member field 'com.jetbrains.php.lang.psi.stubs.PhpStubElementType FUNCTION'
	at com.github.nvelychenko.drupalextend.patterns.Patterns$SIMPLE_FUNCTION$2.invoke(Patterns.kt:82)
	at com.github.nvelychenko.drupalextend.patterns.Patterns$SIMPLE_FUNCTION$2.invoke(Patterns.kt:82)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
```
I trimmed the error for readability, the actual trace is way longer than this.
This error is thrown on a Drupal 10.3 project, after clearing the indexes.

**Comment by nvelychenko** [comment]
The problem is fixed in the new release.
